###############################################################################
# window 0
###############################################################################
rename-window t1

# 上下分割
# split-window -t 0 -d
# resize-pane -t 1 -D 15

# 左右分割
split-window -t 0 -h -d
split-window -t 1 -h -d
select-layout even-horizontal

###############################################################################
# window 1
###############################################################################
new-window -n t2

### 上下分割
##split-window -t 0 -d
### resize-pane -t 1 -D 15

### 左右分割
split-window -t 0 -h -d
split-window -t 1 -h -d
select-layout even-horizontal

#################################################################################
### window 2
#################################################################################
new-window -n t3

### 左右分割
split-window -t 0 -h -d
split-window -t 1 -h -d
select-layout even-horizontal


