set number

" vim起動時のみruntimepathにneobundle.vimを追加
if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.vim/bundle/neobundle.vim
endif

" neobundle.vimの初期化
" NeoBundleを更新するための設定
call neobundle#begin(expand('~/.vim/bundle'))
NeoBundleFetch 'Shougo/neobundle.vim'

" 読み込むプラグインを記載
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimfiler.vim'
NeoBundle 'itchyny/lightline.vim'

NeoBundle 'plasticboy/vim-markdown'
NeoBundle 'kannokanno/previm'
NeoBundle 'tyru/open-browser.vim'

NeoBundle 'fuenor/qfixgrep'
NeoBundle 'fuenor/qfixhowm'

call neobundle#end()

" 読み込んだプラグインも含め、ファイルタイプの検出、ファイルタイプ別プラグイン/インデントを有効化する
filetype plugin indent on

" インストールのチェック
"NeoBundleCheck


" qfixappにruntimepathを通す(パスは環境に合わせてください)
set runtimepath+=c:/temp/qfixapp
" キーマップリーダー
let QFixHowm_Key = 'g'
" howm_dirはファイルを保存したいディレクトリを設定
let howm_dir             = 'D:\mywork\vim_memo'
let howm_filename        = '%Y/%m/%Y-%m-%d-%H%M%S.md'
let QFixHowm_FileType    = 'markdown'

let howm_fileencoding    = 'cp932'
let howm_fileformat      = 'dos'
